### ISSUE TITLE
auto-vectorization in @summarize

### ISSUE THREAD

**Issue by fredcallaway** [TidierOrg/TidierData.jl#50] opened 2023-09-27 15:36 UTC
The docs state that you never auto-vectorize within a @summarize. I think this is a mistake because it is inconsistent with dplyr, and leads to incorrect results in common use cases. For example:

```r
df = tibble(x = c(0,0,1,1))
summarise(df, y = mean(x == 0))

# A tibble: 1 × 1
      y
  <dbl>
1   0.5
````

```julia
df = DataFrame(x = [0,0,1,1])
@summarize df y = mean(x == 0)

1×1 DataFrame
 Row │ y
     │ Float64
─────┼─────────
   1 │     0.0
```

What's the motivation for not auto-vectorizing here? One possible solution that occurred to me is to not auto-vectorize the top level function (here, `mean`) but vectorize everything else. Although, I think the best solution here is probably to have a consistent rule across all verbs: auto-vectorize everything except functions in the lookup table.

**Comment by kdpsingh** [comment] 2023-09-27 16:22
Thank you for this feedback, and I think you make a great point. This behavior dates back to before we had implemented the tilde `~` as a way to opt out of auto-vectorization at the function-level.

I think you're right that we may no longer need this, and I appreciate your sharing an example where this fails.

Let me modify this and see if any of our tests fail.

**Comment by rdboyes** [comment] 2023-12-04 16:00
I ran into something similar doing advent of code today - I now realize that summarize does not autovectorize, but it was unexpected behaviour for me that summarize and mutate don't work the same way, e.g. 

```
#works
@chain DataFrame(a = [1,2,3]) begin
    @mutate(b = 2^(a-1))
end

# doesn't work
@chain DataFrame(a = [1,2,3]) begin
    @summarize(b = sum(2^(a-1)))
end

# works
@chain DataFrame(a = [1,2,3]) begin
    @summarize(b = sum(2 .^(a .- 1)))
end
```

If this is the intended way for `@summarize` to work I think we may need to extend the documentation a bit -

**Comment by fredcallaway** [comment] 2023-12-04 16:57
Documented or not, this issue is the reason I'm still using DataFramesMeta. Any update @kdpsingh ?

**Comment by kdpsingh** [comment] 2023-12-04 17:53
I will fix this. Seeing those examples is really helpful for me.

I opened an issue last week that `across()` should also apply the same auto-vectorization so that it behaves consistently with the rest of the package. We will do the same for `summarize()` barring any unforeseen complications.

@fredcallaway, if auto-vectorization was applied consistently across the package (as I'm planning to do in a fix), is that what you are looking for?

Or would you like to be able to turn auto-vectorization off completely?

**Comment by fredcallaway** [comment] 2023-12-04 18:10
I think auto-vectorizing everywhere (not including the special cases like sum, mean, etc...) is the right approach.

Having a global flag to disable auto-vectorization is an interesting idea, but I can't think of any other package that does something like this, which makes me think it's not good practice.

**Comment by kdpsingh** [comment] 2023-12-04 18:26
This is totally doable. I agree I would want the avoid the flag approach because it could change code behavior and mess with reproducibility.

All functions are currently vectorized except for the ones documented in: https://github.com/TidierOrg/TidierData.jl/blob/adb12bc1210e685b61f307d72030af820f540001/src/TidierData.jl#L29

Which says:
```julia
const not_vectorized = Ref{Vector{Symbol}}([:esc, :Ref, :Set, :Cols, :(:), :∘, :lag, :lead, :ntile, :repeat, :across, :desc, :mean, :std, :var, :median, :first, :last, :minimum, :maximum, :sum, :length, :skipmissing, :quantile, :passmissing, :cumsum, :cumprod, :accumulate, :is_float, :is_integer, :is_string, :cat_rev, :cat_relevel, :cat_infreq, :cat_lump, :cat_reorder, :cat_collapse, :cat_lump_min, :cat_lump_prop, :categorical, :as_categorical, :is_categorical])
```

What's cool is that this array is modifiable, so packages depending on or wanting to be compatible with TidierData.jl could add other functions to this list if they wanted to.

Here's my plan:
- [ ] Make sure `@summarize()` uses this list
- [ ] Make sure `across()` uses this list

**Comment by kdpsingh** [comment] 2023-12-04 18:29
@rdboyes, the reasons you had to add dot-vectorization to your Advent of Code example from https://x.com/randyboyes/status/1731688504730530121?s=46&t=PEX2NKcgCDoTOe3kHQFmDA are:

1. `across()` doesn't currently vectorize functions.
2. `length()` is on the do-not-vectorize list (on the presumption that it usually is intended to return a single value for non-nested data).

**Comment by fredcallaway** [comment] 2023-12-04 18:38
> What's cool is that this array is modifiable, so packages depending on or wanting to be compatible with TidierData.jl could add other functions to this list if they wanted to.

That is cool! It would be great to have an end-user interface as well, something like

```julia
myreducer(x) = sum(filter(iseven, x))
TidierData.disable_autovectorize(:myreducer)
```

**Comment by kdpsingh** [comment] 2023-12-04 19:33
> That is cool! It would be great to have an end-user interface as well, something like
> 
> 
> 
> ```julia
> 
> myreducer(x) = sum(filter(iseven, x))
> 
> TidierData.disable_autovectorize(:myreducer)
> 
> ```

Right now, this isn't documented but should work:

```julia
push!(TidierData.not_vectorized[], :myreducer)
```

I have thought about exposing the interface through functions as well, akin to what you suggested.

**Comment by kdpsingh** [comment] 2023-12-05 07:05
This is now fixed and a fix is on its way to the registry. I’ve updated the documentation on auto-vectorization as well: https://tidierorg.github.io/TidierData.jl/latest/examples/generated/UserGuide/autovec/

**Closed** 2023-12-05 07:06 UTC

**Comment by kdpsingh** [comment] 2023-12-05 07:08
For the original use case:

```julia

julia> df = DataFrame(x = [0,0,1,1])
4×1 DataFrame
 Row │ x     
     │ Int64 
─────┼───────
   1 │     0
   2 │     0
   3 │     1
   4 │     1

julia> @summarize df y = mean(x == 0)
1×1 DataFrame
 Row │ y       
     │ Float64 
─────┼─────────
   1 │     0.5
```
